### ISSUE TITLE
pages dev mode Os

### ISSUE THREAD

**Issue by joelthorner** [joelthorner/TLmanaGer#21]

**Comment by joelthorner** [comment]
Test dev console code:

```javascript
jQuery('.pagesGroupContainer .positionLabel').each(function(){
	var txt = jQuery(this).text();
	var pos = txt.match(/.{1,}\s/g);
	var txtNoN = txt.replace(new RegExp('.{1,}\\s', 'g'), '')
	
	jQuery(this).html(pos + '<span class="n">' + txtNoN + '</span>')
});
```

```css
div.pagesWindowTree div.pagesTreeContainer{
	display: flex;
	flex-wrap: wrap;
}
div.pagesWindowTree div.pagesTreeContainer div.pagesGroupContainer {
    overflow: hidden;
    margin-bottom: 15px;
    border: 1px solid #b2b2b2;
    width: 20%;
    float: left;
    box-sizing: border-box;
    margin-left: -1px;
}


div.pagesWindowTree div.pagesTreeContainer div.pagesGroup > div.positionLabel {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 75%;
    overflow: hidden;
    padding-right: 15px;
    text-align: right;
    white-space: nowrap;
    color: red;
    font-weight: bold;
    font-size: 13px;
}
```
