### ISSUE TITLE
LC trackers view textarea

### ISSUE THREAD

**Issue by joelthorner** [joelthorner/TLmanaGer#291]
```css
[name="trackingCode"] {
    font-family: SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace;
}
```

Afegir hidden feature
